#!/bin/bash

#File is located in /
echo "Deleting the html page"
sleep 2
rm -rf www.chiark.greenend.org.uk/ 
echo "Updating the mirror."
sleep 2
wget -mkEpnp https://www.chiark.greenend.org.uk/~sgtatham/bugs-ru.html
echo "The mirror is updated."
